# Generated by Django 5.0 on 2024-02-26 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.opening'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='revisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='cashflow.runner'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='runner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.runner'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.transactiondetail'),
        ),
    ]
