# Generated by Django 5.0 on 2024-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='modify_duration',
            field=models.DurationField(auto_created=True),
        ),
    ]
