# Generated by Django 5.0 on 2024-02-28 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_transaction_modify_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='modify_duration',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
