# Generated by Django 5.0.2 on 2024-03-09 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.BooleanField(default=False)),
                ('mon', models.BooleanField(default=False)),
                ('tues', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thurs', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.memberjob')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.shift')),
                ('shift_duration', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.shiftduration')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('is_dayoff', models.BooleanField(default=False)),
                ('current_date', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.attendanceday')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.member')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.shift')),
                ('shift_duration', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='attendance.shiftduration')),
            ],
            options={
                'unique_together': {('member', 'current_date')},
            },
        ),
    ]
