# Generated by Django 5.0 on 2024-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='local_ip',
            field=models.CharField(default='192.168.1.1', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('local_ip', 'current_date')},
        ),
    ]
